version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: nota10-db
    restart: always
    environment:
      POSTGRES_USER: deployer_admin
      POSTGRES_PASSWORD: 'A!S@d3f4g5h6'
      POSTGRES_DB: nota10_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nota10-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
